name: sleep-ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - mne
  - tqdm
  - jupyterlab
  - pyedflib
  - scipy
  - numpy
  - scikit-learn
  - pandas
  - matplotlib
  - ipykernel
  - neurokit2
prefix: D:\Miniconda\Miniconda\envs\sleep-ml